# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Automated-Testing-Framework

on:  
  workflow_dispatch:
    inputs:
      Run_API_Tests:
        type: boolean
        description: "Run API tests"
        required: true
        default: true

      Run_UI_Tests:
        type: boolean
        description: "Run UI tests"
        required: true
        default: true

      Browser:
        type: choice
        description: "Choose the browser type"
        options:
        - "Chrome"
        - "Firefox"
      Timeout:
        description: "Please, specify time for waiting Web-Elements"
        required: true
        default: "30"
  push:
    branches:
      - 'Github-Action-Temp'
      - 'main'
  pull_request:
    branches:
      - 'Github-Action-Temp'
      - 'main'
  schedule:
    - cron: '0 0 * * *'
    
env:
  DOTNET_VERSION: '7.0.100'
  SELENIUN_GRID_VERSION: '4.6.0'
  PORT_1: '5555'
  PORT_2: '6666'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup Java
        if: ${{ github.event.inputs.Run_UI_Tests }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Start Selenium Hub
        if: ${{ github.event.inputs.Run_UI_Tests }}
        run: "java -jar selenium-server-${{ env.SELENIUN_GRID_VERSION }}.jar hub &"

      - name: Start Selenium Port ${{ env.PORT_1 }}
        if: ${{ github.event.inputs.Run_UI_Tests }}
        run: "java -jar selenium-server-${{ env.SELENIUN_GRID_VERSION }}.jar node --port ${{ env.PORT_1 }} &"

      - name: Start Selenium Port ${{ env.PORT_2 }}
        if: ${{ github.event.inputs.Run_UI_Tests }}
        run: "java -jar selenium-server-${{ env.SELENIUN_GRID_VERSION }}.jar node --port ${{ env.PORT_2 }} &"
     
      - name: "Setup Chrome"
        if: ${{ github.event.inputs.Run_UI_Tests }} && ({{ github.event.inputs.Browser }} == Chrome) 
        uses: browser-actions/setup-chrome@latest
      
      - name: "Setup Firefox"
        if: ${{ github.event.inputs.Run_UI_Tests }} && ({{ github.event.inputs.Browser }} == Firefox) 
        uses: browser-actions/setup-firefox@latest

      - name: Edit Browser value in Configuration.json   
        if: ${{ github.event.inputs.Run_UI_Tests }}
        uses: MerthinTechnologies/edit-json-action@v1
        with:
          filename: '${{ github.workspace }}/Tests/Configuration.json'
          key: 'Browser'
          value: '${{ github.event.inputs.Browser }}'
          
      - name: Edit Timeout value in Configuration.json  
        if: ${{ github.event.inputs.Run_UI_Tests }} 
        uses: MerthinTechnologies/edit-json-action@v1
        with:
          filename: '${{ github.workspace }}/Tests/Configuration.json'
          key: 'Timeout'
          value: '${{ github.event.inputs.Timeout }}'

      - name: Run_Api_Tests
        if: ${{ github.event.inputs.Run_API_Tests }} 
        run: dotnet test --filter TestCategory="ApiTest"

      - name: Run_UI_Tests
        if: steps.Run_Api_Tests.outputs.status == 'failure' || steps.world.Run_Api_Tests.status == 'success'
        run: dotnet test --filter TestCategory!="ApiTest"

      - name: Publishing artifacts
        if: steps.Run_UI_Tests.outputs.status == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: Failed test
          path: ${{ github.workspace }}/Tests/bin/Debug/net7.0/**.Jpeg