# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Automated-Testing-Framework

on:  
  workflow_dispatch:
    inputs:
      Browser:
        description: "Please, specify browser type (Chrome or Firefox)"
        required: true
        default: "Chrome"
      Timeout:
        description: "Please, specify time for waiting Web-Elements"
        required: true
        default: "30"
  push:
    branches:
      - 'Github-Action-Temp'
      - 'main'
  pull_request:
    branches:
      - 'Github-Action-Temp'
      - 'main'
  schedule:
    - cron: '0 0 * * *'
    
env:
  DOTNET_VERSION: '7.0.100' # The .NET SDK version to use

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup Google Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Running Google Chrome
      run: chrome --version
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Print variables
      run:  echo "WORKSPACE is ${{ github.workspace }}, Browser is ${{ inputs.Browser }}, Timeout is ${{ inputs.Timeout }}"
        
    - name: Edit Browser value in Configuration.json   
      uses: MerthinTechnologies/edit-json-action@v1
      with:
        filename: '${{ github.workspace }}/Tests/Configuration.json'
        key: 'Browser'
        value: '${{ inputs.Browser }}'
        
    - name: Edit Timeout value in Configuration.json   
      uses: MerthinTechnologies/edit-json-action@v1
      with:
        filename: '${{ github.workspace }}/Tests/Configuration.json'
        key: 'Timeout'
        value: '${{ inputs.Timeout }}'

    - name: Run Api Tests
      run: dotnet test --no-build --verbosity normal --filter TestCategory="ApiTest"

    - name: Run UI Tests
      run: dotnet test --no-build --verbosity normal --filter TestCategory!="ApiTest"